environment:
 _DOTNET_VERSION: "6.0.100-rc.2.21505.57"

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# scripts that run after cloning repository
install:
 - ps: "[Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
 - ps: Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
 - ps: if ((-Not (Test-Path .\dotnet.exe)) -or (((.\dotnet.exe --version) -Join '') -ne $Env:_DOTNET_VERSION)) { .\dotnet-install.ps1 -Version $Env:_DOTNET_VERSION -InstallDir .\dotnet } else { $Env:path = $Env:APPVEYOR_BUILD_FOLDER + "\dotnet\dotnet.exe;" + $Env:path }

# scripts to run before build
before_build:
  - dotnet --info

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: .\build.ps1 --target=AppVeyor

# scripts to run after build
after_build:

# Tests
test: off

# Branches to build
branches:
  only:
    - develop
    - master
    - main
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
  - tools -> build.cake

# Environment configuration
image:
  - Ubuntu1804
  - Visual Studio 2019

#  Skip builds for doc changes
skip_commits:
  message: /\(doc\).*/
